#! /bin/bash

export TOTAL_MEM=$(nvidia-smi -q -d MEMORY | grep "Total" | head -n 1 | tr -s ' ' | cut -d ' ' -f 4)
export USED_MEM=$(nvidia-smi -q -d MEMORY | grep "Used" | head -n 1 | tr -s ' ' | cut -d ' ' -f 4)
export MEM_UTILIZATION=$(echo "scale=1; 100*$USED_MEM/$TOTAL_MEM" | bc)

echo "${MEM_UTILIZATION}%"
