#!/bin/bash
# Copyright (C) 2014 Alexander Keller <github@nycroth.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#------------------------------------------------------------------------

#INTERFACE="${BLOCK_INSTANCE:-wlan0}"
# check to see what value to plug in here with "ifconfig | grep RUNNING | grep BROADCAST"
INTERFACE=$(ifconfig | grep wlp | cut -d ":" -f1)

#------------------------------------------------------------------------

# As per #36 -- It is transparent: e.g. if the machine has no battery or wireless
# connection (think desktop), the corresponding block should not be displayed.
# [[ ! -d /sys/class/net/${INTERFACE}/wireless ]] ||
    # [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]] && exit

#------------------------------------------------------------------------

#QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
QUALITY=$(cat /proc/net/wireless | grep $INTERFACE | awk '{ print int($3 * 100 / 70) }')

#------------------------------------------------------------------------

echo $QUALITY% # full text
echo $QUALITY% # short text

# color
if (( QUALITY >= 80 )); then
	echo "#98971a"
elif (( QUALITY < 80 && QUALITY >= 60 )); then
	echo "#d79921"
elif (( QUALITY < 60 && QUALITY >= 40 )); then
	echo "#d65d0e"
elif (( QUALITY < 40 )); then
	echo "#cc241d"
fi
