#!/bin/bash

QUALITY=$(nmcli -f IN-USE,SIGNAL dev wifi | grep "^\*" | awk '{print $2}')


echo $QUALITY%
echo $QUALITY%

# color
if (( QUALITY >= 80 )); then
	echo "#98971a"
elif (( QUALITY < 80 && QUALITY >= 60 )); then
	echo "#d79921"
elif (( QUALITY < 60 && QUALITY >= 40 )); then
	echo "#d65d0e"
elif (( QUALITY < 40 )); then
	echo "#cc241d"
fi
